"""
# CreateUserInput

## desc
...
"""
input CreateUserInput {
  """
  First Name
  """
  firstName: String!

  """
  Last Name
  """
  lastName: String!

  """
  FullName
  """
  fullName: String!
}
